export const CHANGE_SEARCHTERM1 = 'CHANGE_SEARCHTERM1'
export const CHANGE_SEARCHTERM2 = 'CHANGE_SEARCHTERM2'

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING'
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS'
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED'